"""
generate_report.py
Consolidates SAST, dependency scan, and DAST results into a single markdown report.
"""

import json
import os
from datetime import datetime

REPORTS_DIR = "all-reports"
OUTPUT_DIR = "reports"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return None


def parse_bandit(data):
    if not data:
        return "⚠️ Report not found", []
    results = data.get("results", [])
    high = [r for r in results if r.get("issue_severity") == "HIGH"]
    medium = [r for r in results if r.get("issue_severity") == "MEDIUM"]
    low = [r for r in results if r.get("issue_severity") == "LOW"]
    summary = f"🔴 High: {len(high)} | 🟡 Medium: {len(medium)} | 🟢 Low: {len(low)}"
    findings = []
    for r in high + medium:
        findings.append({
            "severity": r.get("issue_severity"),
            "title": r.get("issue_text"),
            "file": r.get("filename"),
            "line": r.get("line_number"),
            "cwe": r.get("issue_cwe", {}).get("id", "N/A"),
        })
    return summary, findings


def parse_pip_audit(data):
    if not data:
        return "⚠️ Report not found", []
    vulns = data.get("dependencies", [])
    vulnerable = [d for d in vulns if d.get("vulns")]
    summary = f"📦 Vulnerable packages: {len(vulnerable)} / {len(vulns)} scanned"
    findings = []
    for pkg in vulnerable:
        for v in pkg.get("vulns", []):
            findings.append({
                "package": pkg.get("name"),
                "version": pkg.get("version"),
                "vuln_id": v.get("id"),
                "fix": v.get("fix_versions", ["No fix available"]),
                "description": v.get("description", "")[:120],
            })
    return summary, findings


def find_report(name):
    """Search recursively in all-reports for a file matching name."""
    for root, dirs, files in os.walk(REPORTS_DIR):
        for f in files:
            if f == name:
                return os.path.join(root, f)
    return None


def build_markdown(bandit_summary, bandit_findings, dep_summary, dep_findings):
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# 🔐 SecurePipe — Security Summary Report",
        f"**Generated:** {now}  ",
        f"**Pipeline:** GitHub Actions DevSecOps  ",
        "",
        "---",
        "",
        "## 📊 Executive Summary",
        "",
        "| Tool | Result |",
        "|------|--------|",
        f"| Bandit (SAST) | {bandit_summary} |",
        f"| pip-audit (Deps) | {dep_summary} |",
        "| OWASP ZAP (DAST) | See ZAP artifact for full report |",
        "",
        "---",
        "",
        "## 🔍 SAST Findings (Bandit)",
        "",
    ]

    if bandit_findings:
        lines.append("| Severity | Issue | File | Line | CWE |")
        lines.append("|----------|-------|------|------|-----|")
        for f in bandit_findings:
            lines.append(f"| {f['severity']} | {f['title']} | `{f['file']}` | {f['line']} | CWE-{f['cwe']} |")
    else:
        lines.append("✅ No high/medium severity findings.")

    lines += [
        "",
        "---",
        "",
        "## 📦 Dependency Findings (pip-audit)",
        "",
    ]

    if dep_findings:
        lines.append("| Package | Version | Vuln ID | Fix Available |")
        lines.append("|---------|---------|---------|---------------|")
        for f in dep_findings:
            fix = ", ".join(f["fix"]) if isinstance(f["fix"], list) else f["fix"]
            lines.append(f"| {f['package']} | {f['version']} | {f['vuln_id']} | {fix} |")
    else:
        lines.append("✅ No vulnerable dependencies found.")

    lines += [
        "",
        "---",
        "",
        "## 🌐 DAST Findings (OWASP ZAP)",
        "",
        "Download the `zap-dast-report` artifact for the full HTML/JSON ZAP report.",
        "",
        "---",
        "",
        "## 🛠️ Recommended Remediations",
        "",
        "1. **Replace hardcoded secrets** with environment variables or a secrets manager",
        "2. **Use parameterized queries** to prevent SQL injection",
        "3. **Avoid `shell=True`** in subprocess calls with user-controlled input",
        "4. **Update Jinja2** to latest version to patch known CVEs",
        "",
        "---",
        "*Report generated by SecurePipe automated security pipeline*",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    bandit_path = find_report("bandit-report.json")
    dep_path = find_report("pip-audit-report.json")

    bandit_data = load_json(bandit_path)
    dep_data = load_json(dep_path)

    bandit_summary, bandit_findings = parse_bandit(bandit_data)
    dep_summary, dep_findings = parse_pip_audit(dep_data)

    report = build_markdown(bandit_summary, bandit_findings, dep_summary, dep_findings)

    output_path = os.path.join(OUTPUT_DIR, "security-summary.md")
    with open(output_path, "w") as f:
        f.write(report)

    print(f"✅ Security summary written to {output_path}")
    print(f"\n{report}")
